### ISSUE TITLE
Turning sensor on camera click

### ISSUE THREAD

**Issue by akarokr** [Alexey-Danilchenko/Kodak-DCS-Tools#2]
This is not an issue, but I would like to know if it is possible to turn the sensor on when I click with the camera and using the buttom in the back. It is possible? It only takes software modifications or I have to "change" the hardware?

PS: I did't find your email, so I sent my question here. Feel free to contact me by email and delete this issue. My email is luiz.moura.n@gmail.com.

**Comment by Alexey-Danilchenko** [comment]
Which sensor on what camera? Sensors are enabled by firmware when and as needed on ProBacks and SLR/n/c
