### ISSUE TITLE
Camera to lens communication

### ISSUE THREAD

**Issue by marek-maczko** [Alexey-Danilchenko/Kodak-DCS-Tools#3]
Hi,
I would like to ask if you reverse engineered also a camera to lens communication and vice versa? or is it the same as camera to DB? 
If I understand your wiki correctly, you reverse engineered communication between Digital back (sensor) and camera (body).
I would appreciate if your reply here in to my email adress ... marek.maczko3@gmail.com

Best Regards,
Marek

**Comment by Alexey-Danilchenko** [comment]
If you talking about ProBacks and not SLR cameras then camera to lens comminication has nothing to do with the digital back. It is controlled by respective cameras (Mamiya/Phase One, Contax and Hasselblad). Reverse engineering of communication protocol is possible when you have some code to work with (in this case Digital back). Working out from scratch the protocol between 2 unknown devices is nearly impossible. It also has nothing to do with Kodaks which are the point of this whole repository.

**Comment by marek-maczko** [comment]
We have only the lens (phase one 80mm AF/2.8).. And i was asking if its
possible to use your code to communicate with lense from camera.. And also
if there is difference in protocol while communicating between camera and
lens, camera and Digital back..

Dňa pi 17. 7. 2020, 11:48 Alexey-Danilchenko <notifications@github.com>
napísal(a):

**Comment by Alexey-Danilchenko** [comment]
> We have only the lens (phase one 80mm AF/2.8).. And i was asking if its possible to use your code to communicate with lense from camera.. And also if2 there is difference in protocol while communicating between camera and lens, camera and Digital back.

I believe I already answered that - "camera to lens comminication has nothing to do with the digital back".  Please do apply common sense here - the lens and camera is a single system and the digital back is external produced by many other manufacturers to start with and as such they serve different purpouse and have different interfaces. At the very least so start with looking at the reversed protocol that I have done to see that it is hardly suitable for anything but digital back.

**Comment by marek-maczko** [comment]
Ok, just wanted to be sure if I understand it correctly,
Thank for your reply
